print("hi welcome to madlibs lets start!")
first=input("enter a noun")
second=input("enter the name of a place")
third=input("enter a animal name")
fourth=input("enter your favourite food")
fifth=input("enter a outdoor activity you enjoy doing")
sixth=input("Finally,name your favourite singers name")
print("Now lets hear your story.")
print("Once upon a time there was a big frog called " + str(first)+ ". He lives in "+str(second)+"his best friend was a "+str(third)+"he loved eating"+str(fourth)+"his favourite game is"+str(fifth)+"he bought us tickets to attend the concert of"+str(sixth)
